### PR TITLE
fixes css batch setting on non-existing element, fixes #1145

### LINKED ISSUE #1145: `$().css(object)` should not return `undefined`
`.css({height: 1, width: 2})` on non-existing element should return `this` instead of `undefined`, because when calling this, user intend to set the value but not to get the computed style of the element.

```js
$().css({
  height: 1
}).css({
  width: 1
});
``` 

- expected: ok, jquery does it so.

- actual: `Uncaught TypeError: Cannot read property 'css' of undefined`

### PR DESCRIPTION
**Pull request by kaelzhang**
- fixes `$().css({height:1}).css({height:1})`
- adds test cases
- fixes #1145

Have tried my best to obey the original coding style. Duplicate `getComputedStyle(element, '')`, but it will not become much larger after compressing.

### CODE REVIEW

File: src/zepto.js [hunk 1]
```diff
@@ -690,18 +690,19 @@ var Zepto = (function() {
...
+        var element = this[0]
+        if (typeof property == 'string') {
+          if (!element) return
+          return element.style[camelize(property)] || getComputedStyle(element, '').getPropertyValue(property)
+        } else if (isArray(property)) {
+          if (!element) return
           var props = {}
           $.each(property, function(_, prop){
-            props[prop] = (element.style[camelize(prop)] || computedStyle.getPropertyValue(prop))
+            props[prop] = (element.style[camelize(prop)] || getComputedStyle(element, '').getPropertyValue(prop))
```
Comment (mislav) [inline src/zepto.js]: This calls `getComputedStyle(element, '')` in a loop for every property name, but it will always have the same result, so calling it many times is wasteful. Can you cache it outside of the loop in a `computedStyle` variable like it was before? Thanks

File: test/zepto.html [hunk 2]
```diff
@@ -1653,12 +1653,18 @@
 
       testCSSOnNonExistingElement: function (t) {
         var errorWasRaised = false
+        var el = $('.some-non-exist-elm')
         try {
-          var color = $('.some-non-exist-elm').css('color')
+          var color = el.css('color')
+          var ret = el.css({
```
Comment (mislav) [inline test/zepto.html]: This is a good test, but can you add a separate test case for it? Maybe call it something like `testCSSOnNonExistingElementReturnsSelf`. You also don't need `try…catch` blocks in that test case. Then you can leave this test case unchanged.

**Comment by kaelzhang** [comment]
Catch ya, I'll look into it right now.

**Comment by kaelzhang** [comment]
The duplication of `getComputedStyle(element, '')` makes the code not that perfect, but it could not be neater, because the logic grows a little more complicated.
